- name: Installs s3cmd dependencies
  apt: 
    name:
      - python-magic
    state: present

- name: Ensure that apt s3cmd is not present
  apt: 
    name:
      - s3cmd
    state: absent

- name: install s3cmd from source
  git:
    repo=https://github.com/s3tools/s3cmd.git
    dest=/usr/local/src/s3cmd

- name: Setup symlink to /usr/local/bin
  file:
    src=/usr/local/src/s3cmd/s3cmd
    dest=/usr/local/bin/s3cmd
    owner=root
    group=root
    state=link

- name: Adds s3 credentials
  template: >
    src=../templates/s3cfg.j2
    dest=~{{ s3cmd_user }}/.s3cfg
    owner={{ s3cmd_user }}
    mode=600
